### ISSUE TITLE
covid_560 is missing from the count matrix RDS files on GEO 

### ISSUE THREAD

**Issue by ttriche** [ajwilk/2020_Wilk_COVID#2]
The entry states that 8 patient samples and 6 control samples were run, but only 7 covid samples have GSM entries, and the raw data reflects this.  Discovered while matching covariate CSV to data...

https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE150728

Please fix?

**Comment by ajwilk** [comment]
Thanks for bringing this up. The missing patient is C6 (AKA 560), and we cannot share sequence-level data (eg. fastqs) for this patient as they explicitly did not consent to that. That's why it's not on GEO. But, we can share other levels of processed data for this patient, so I've uploaded the raw, unfiltered count matrices (spliced/unspliced/spanning) for this patient in `data/count_matrices`
