### ISSUE TITLE
Confused about cell annotation in "covid_analysis_markdown.Rmd"

### ISSUE THREAD

**Issue by malihhhh** [ajwilk/2020_Wilk_COVID#8]
Thank you for providing the code for everyone to learn. I have a little question. You divided cell type in this way here, but cluster 23 and cluster 21 have the same annotation ("IgA PB"), and  cluster 21 belong to covid_B.idents, but cluster 23 not. Why? What's more, I don't know why clusters 24 and 27 are divided in covid_B.idents. 
Looking forward to your reply.
```
covid_myeloid.idents <- c("3", "6", "7", "8", "10", "20", "24", "25", "26", "27", "28")
covid_B.idents <- c("5", "9", "16", "18", "21", "24", "27", "29")
covid_fine.idents <- c("NK", "CD8m T", "CD4m T", "CD14 Monocyte", "CD4n T", "B", "CD14 Monocyte", "CD14 Monocyte", "CD14 Monocyte", "IgM PB", "CD16 Monocyte", "NK", "RBC", "CD8eff T", "RBC", "CD8m T", "IgG PB", "Platelet", "IgG PB", "CD4 T", "DC", "IgA PB", "gd T", "IgA PB", "SC & Eosinophil", "Neutrophil", "pDC", "Developing Neutrophil", "CD16 Monocyte", "IgA PB")
```

**Comment by ajwilk** [comment]
Hi @malihhhh, sorry for the delay, have been on holiday. Thanks for your question, ```covid_B.idents``` was meant as a B cell catch-all for exploratory analyses. Cluster 27 (developing neutrophils) was included given their phenotypic similarity to plasmablasts in our dataset and because we weren't sure what to call these cells in the beginning. You are right, there is no difference between clusters 21 and 23 in terms of broad cell type identity. 

Feel free to re-open if you have more questions on this topic. Also, I'll point you to our recent preprint that discusses a much larger extension of this dataset: https://www.biorxiv.org/content/10.1101/2020.12.18.423363v1 We're working to share data and code for that very soon, and depending on what you're interested in re-analyzing it will likely be a more interesting/useful dataset than this one.

**Comment by malihhhh** [comment]
> Hi @malihhhh, sorry for the delay, have been on holiday. Thanks for your question, `covid_B.idents` was meant as a B cell catch-all for exploratory analyses. Cluster 27 (developing neutrophils) was included given their phenotypic similarity to plasmablasts in our dataset and because we weren't sure what to call these cells in the beginning. You are right, there is no difference between clusters 21 and 23 in terms of broad cell type identity.
> 
> Feel free to re-open if you have more questions on this topic. Also, I'll point you to our recent preprint that discusses a much larger extension of this dataset: https://www.biorxiv.org/content/10.1101/2020.12.18.423363v1 We're working to share data and code for that very soon, and depending on what you're interested in re-analyzing it will likely be a more interesting/useful dataset than this one.

Thank you for your reply, this new article is great. Looking forward to your sharing of data and code.
